version: 1.0.{build}

image: Visual Studio 2017

install:
  - ps: cd rescomp
  - ps: mkdir deps
  - ps: cd deps
  - curl -L https://github.com/nohajc/llvm-clang-static-libs-prebuilt/releases/download/v6.0.1/llvm-clang-6.0-libs-win-x64.7z -o llvm-clang-6.0-libs-win-x64.7z
  - 7z x llvm-clang-6.0-libs-win-x64.7z -aoa
  - ps: cd ..\..

platform: x64
configuration: Release

build:
  project: rescomp/rescomp.vcxproj

after_build:
  - build_scripts/win/appveyor_package.bat

artifacts:
  - path: "resman-$(appveyor_repo_tag_name)-win-amd64.zip"
    name: resman-win-amd64

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: Jt5nGerAEIzy6Ghn8C5HVqXS1tAzrCQ46BJ5D2bjAiR6EE198sRLKVkfzSaTOsQk
    artifact: resman-win-amd64
  on:
    branch: master
    appveyor_repo_tag: true
