sudo: required

services:
  - docker

osx_image: xcode10
dist: trusty

os:
  - osx
  - linux

language: cpp

install:
  - build_scripts/${TRAVIS_OS_NAME}/travis_install.sh

script:
  - build_scripts/${TRAVIS_OS_NAME}/travis_script.sh

deploy:
  provider: releases
  api_key:
    secure: Es7AIr8dGX79EBtpDSvk/IvfnZwFdkNg62vAoqBUmsRQfPuB9NroAU0urosOBvAKRKhY7+frtFlv4P4HXlinLXr+HkUnmaxFtOqJjcP6l5jMrJUCiM5E73amN1tBxcpAkHccMyiSWScKNCmjFQ8pj6DJ4IgAtdumy/yqgKWcBPkUF/k3X8XODpwTwVNbW1UkdL3TuMLlCzNCEV9Gj/6cZrkJS94/VFNW+Sb+4TQnugE2sdVMgGIpxF1TVw8GYliPDftkYS0mphzBz+YUNyvl+SvcAXOY05d2iijGnw/UlTSIn0QeMuJgDdZ/JtSeu1T04uaiiy7tQn1maKm9AA+uLKqb6uoVv7I6w5n4vUhfc1w6SVA4bk/LeJ33ssNA41AkohfV1/Ome7PV6riFOiKq/W1XVtDMeckZUF+Cm7YNMuJ+IFp1Xutw4/7/XaiC0QbnEn8ip3aCHHkpffMP2v+4bBOUg4jSae96UmvvyvsgeTZHckBg/Rj5MkQbFkip/rB4yHKat3HYQrMCPXdtouO7DDCUu9ibFfXBJE7GAZD2SguXIaIwbXQX3CIsVZYAq++SSaKBdjGNfHjGINxHSsUjma94Qkv1rZnNMVpNCmLwx9UA0Crau2hQsgrO5nJ2EgJkCoxY0fuwHrCS97FeEZP89g7xr4bgQm08B18VYbmbDdQ=
  file: build/resman-${TRAVIS_OS_NAME}-amd64.tar.xz
  skip_cleanup: true
  on:
    tags: true
