sudo: required

services:
  - docker

osx_image: xcode10
dist: trusty

os:
  - osx
  - linux

language: cpp

install:
  - build_scripts/${TRAVIS_OS_NAME}/travis_install.sh

script:
  - build_scripts/${TRAVIS_OS_NAME}/travis_script.sh

deploy:
  provider: releases
  api_key:
    secure: "s+aTPutwhmulFr0QLN6Wis5GPF6/Cii9W++DY+xubHP6+5xF2IjvAxHfJuCxhyfVuY8rasVn8yOvh+5nEX2zKcFNTyAsOzExKmFpLZwcLvRXcFsfo6WyQnE2NR6Xamo3iQns8BipSIFD67Ogp5W7q4GYzZJJGEWMIZOMrQx4LBPNeYXy7u9LksEsZPCQA6oYiMMiNvhsnoQMdWtOcCmMFwmEhdw0/Sw+klX6Dn5YuNWV37J1VSsg17Nrkunbgc2GV1S9W9j/zauy7hVW9apvH8Aj2k+t15W8XFxMED0aTy8zqj2lJ5msEZnO9W0XXaSu22nhOtr3cPcGAXRWE0NeGJouXbWFGm29eTqH/lEzDwB8KNWg+OiXUNkzMrFZgrUOTnjQHhc+a9djB3nwrIDn5dRZu/D4xTFfyTdRDaP6cm2T6KUpyUyP254i3tFYlIhklI89sUI7yuFg9msGwDGnv8uTLRyKxJp9Tfsp1uzGAOU+j2K+HmUW1EAAlnxblzP0O1vSFdZt2apWCq5b8MB8OJtsK624GyDX0pbhaQNP9Ykd3cHEeljOGcmrkCZktraBfjcF7U8kAhc23RZA/1S/LfCp27IZxZwNhqAMYVC0CQ0mjFqmx8B5prnA2QyUMHZPmYrNRc7QSeKut1FGVJ2Au7UcPu0kZLJ7HW8MinkZgJs="
    file: build/resman-${TRAVIS_OS_NAME}-amd64.tar.xz
  skip_cleanup: true
  on:
    branch: master
    tags: true
