sudo: required

services:
  - docker

osx_image: xcode10
dist: trusty

os:
  - osx
  - linux

language: cpp

install:
  - build_scripts/${TRAVIS_OS_NAME}/travis_install.sh

script:
  - build_scripts/${TRAVIS_OS_NAME}/travis_script.sh

deploy:
  provider: releases
  api_key:
    secure: quC+gWR49/hmtbQmiuQN8aRj9WURDUU8nTkL/ZxT24w9JQ5mHfI8g+/bRd/EWR1FvSBWRPpYtBFp9MoWUpLVSrCGKpH10QXCzjYbXVoZ48osgBuW9DxIXRDfeYUlVxkWqYC7SVyurrBskJkVJu1KJFL4TDzBLZBl3XahL78gWEBYgwONx21aGWv+AyD2DMfilj7GknsmO9K0FL6Mk+gWzV0kGBrXREkMfW6Qfsll8Ev0ovvGaddVbnHLeKczzXpJs5wG01lIzHDC8LBj22+/S5oEAxgbTHGbzu4w3qpmy8Ucn3tUXQhWVyV0VtoWBY8d4VCn9y934e1JX5IxN6X4XDuiEgXi7hO13w28UbMLmUPv0VYapejnC3iPvkjUXpbhpW/QXcRvhEtLaofU6Ls9ctBTRGzscf7sUtXp/7bfif0+/fCi0UNbH4IR3uOBRIhNU/qOpy3M5T+r0f/jN7B+IXPSaNHFgubeFHkG2Sdhgcgc8bCRTvX3zqTmzsu6czmCI8kEYj3++3kCNBdbple5I9mLjyTkPJqrrwlU37i1GzZM1q3Xtw+4O9Hz0IqL90/PUNFvSBeeVHqd2cLXZrfgBKJ2xMv8j6jnOLJIa7pxN09asZbaBqr+eqDujVmfROsa8XYeyHC5+nd+/Cy5P2kRr0HwOLMVcHeFLHsvDGjbQrk=
  file: build/resman-${TRAVIS_OS_NAME}-amd64.tar.xz
  skip_cleanup: true
  on:
    tags: true
